name: Build APK with Docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build APK using Docker
        run: |
          # Создаём временный Dockerfile для сборки
          cat << 'EOF' > Dockerfile.buildozer
          FROM kivy/buildozer:latest

          USER root
          RUN apt-get update && apt-get install -y \
              libffi-dev \
              libssl-dev \
              libxml2-dev \
              libxslt1-dev \
              libjpeg8-dev \
              zlib1g-dev \
              && rm -rf /var/lib/apt/lists/*

          USER buildozer
          WORKDIR /home/buildozer/hostcwd

          # Копируем файлы проекта
          COPY --chown=buildozer:buildozer . .

          # Создаём buildozer.spec, если его нет
          RUN if [ ! -f "buildozer.spec" ]; then \
                echo "[app]\ntitle = Bar Inventory\npackage.name = barinventory\npackage.domain = org.example\nsource.dir = .\nsource.include_exts = py,png,jpg,kv,atlas,db\nversion = 0.1\nrequirements = python3,kivy,sqlite3\nandroid.api = 34\nandroid.minapi = 21\nandroid.ndk = 25b\nandroid.archs = arm64-v8a\norientation = portrait\nandroid.permissions = INTERNET\nandroid.accept_sdk_license = True\n\n[buildozer]\nlog_level = 2" > buildozer.spec; \
              fi

          # Создаём минимальный main.py, если его нет
          RUN if [ ! -f "main.py" ]; then \
                echo 'print("Hello from APK built with Docker")' > main.py; \
              fi

          # Запуск сборки
          CMD ["buildozer", "-v", "android", "debug"]
          EOF

          # Собираем и запускаем контейнер
          docker build -t my-buildozer -f Dockerfile.buildozer .
          # Монтируем .buildozer и bin для кэширования и получения результата
          docker run --rm \
            -v $(pwd)/.buildozer:/home/buildozer/hostcwd/.buildozer \
            -v $(pwd)/bin:/home/buildozer/hostcwd/bin \
            my-buildozer

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: bar-inventory-apk
          path: bin/*.apk
