name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout код
        uses: actions/checkout@v4
        
      - name: Установка зависимостей
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential python3-dev libffi-dev libssl-dev libmpg123-0 libsqlite3-dev libbz2-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good
          pip install --upgrade pip
          pip install buildozer
          pip install Cython==0.29.33
        
      - name: Сборка APK
        run: |
          buildozer init
          # Настройка спецификаций
          echo 'title = Bar Inventory' >> buildozer.spec
          echo 'package.name = barinventory' >> buildozer.spec
          echo 'package.domain = org.barinventory' >> buildozer.spec
          echo 'source.dir = .' >> buildozer.spec
          echo 'source.include_exts = py,db' >> buildozer.spec
          echo 'requirements = python3,kivy,sqlite3' >> buildozer.spec
          echo 'p4a.hook = hooks/hook-sqlite3.py' >> buildozer.spec
          echo 'android.api = 31' >> buildozer.spec
          echo 'android.minapi = 21' >> buildozer.spec
          echo 'android.ndk = 25b' >> buildozer.spec
          echo 'android.arch = arm64-v8a' >> buildozer.spec
          echo 'orientation = portrait' >> buildozer.spec
          echo 'android.permissions = INTERNET, WRITE_EXTERNAL_STORAGE, READ_EXTERNAL_STORAGE' >> buildozer.spec
          buildozer -v android debug
        
      - name: Загрузка APK
        uses: actions/upload-artifact@v4
        with:
          name: bar-inventory-apk
          path: bin/*.apk