name: Сборка APK

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            build-essential \
            libffi-dev \
            libssl-dev \
            libxml2-dev \
            libxslt1-dev \
            libjpeg-dev \
            zlib1g-dev \
            python3-pip \
            autoconf \
            automake \
            libtool \
            pkg-config \
            libltdl-dev \
            cmake \
            ninja-build

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install Cython==0.29.36
          pip install buildozer

      - name: Create buildozer.spec
        run: |
          echo "[app]" > buildozer.spec
          echo "title = Bar Inventory" >> buildozer.spec
          echo "package.name = barinventory" >> buildozer.spec
          echo "package.domain = org.barinventory" >> buildozer.spec
          echo "source.dir = ." >> buildozer.spec
          echo "source.include_exts = py,db,png,jpg,kv,atlas" >> buildozer.spec
          echo "source.include_patterns = assets/*,res/*,libs/*" >> buildozer.spec
          echo "version = 1.0" >> buildozer.spec
          echo "requirements = python3,kivy==2.2.1,openssl,sqlite3" >> buildozer.spec
          echo "android.api = 33" >> buildozer.spec
          echo "android.minapi = 21" >> buildozer.spec
          echo "android.ndk = 25b" >> buildozer.spec
          echo "android.arch = arm64-v8a" >> buildozer.spec
          echo "orientation = portrait" >> buildozer.spec
          echo "fullscreen = 0" >> buildozer.spec
          echo "android.permissions = INTERNET,WRITE_EXTERNAL_STORAGE,READ_EXTERNAL_STORAGE" >> buildozer.spec
          echo "android.wakelock = False" >> buildozer.spec
          echo "android.allow_backup = True" >> buildozer.spec
          echo "android.accept_sdk_license = True" >> buildozer.spec
          echo "" >> buildozer.spec
          echo "[buildozer]" >> buildozer.spec
          echo "log_level = 2" >> buildozer.spec

      - name: Download Android SDK and NDK
        run: |
          # SDK
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
          mkdir -p android-sdk/cmdline-tools
          unzip cmdline-tools.zip -d android-sdk/cmdline-tools
          mv android-sdk/cmdline-tools/cmdline-tools android-sdk/cmdline-tools/latest
          rm cmdline-tools.zip

          # NDK (исправление: используем r25b, совместимый с API 33)
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip -O android-ndk.zip
          unzip android-ndk.zip
          mv android-ndk-r25b android-ndk
          rm android-ndk.zip

      - name: Setup environment variables
        run: |
          echo "ANDROID_SDK_HOME=$PWD/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=$PWD/android-ndk" >> $GITHUB_ENV
          echo "PATH=$PWD/android-sdk/cmdline-tools/latest/bin:$PWD/android-ndk:$PATH" >> $GITHUB_ENV

      - name: Accept Android SDK Licenses and Install Build Tools
        run: |
          export ANDROID_SDK_HOME=$PWD/android-sdk
          export PATH=$ANDROID_SDK_HOME/cmdline-tools/latest/bin:$PATH
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "build-tools;33.0.0" "platforms;android-33"

      - name: Build APK with Buildozer
        run: |
          buildozer android clean
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: bar-inventory-apk
          path: bin/*.apk