name: Сборка APK

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout код
        uses: actions/checkout@v4

      - name: Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Установка Buildozer и зависимостей
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk
          pip install buildozer

      - name: Создание buildozer.spec
        run: |
          echo "[app]" > buildozer.spec
          echo "title = Bar Inventory" >> buildozer.spec
          echo "package.name = barinventory" >> buildozer.spec
          echo "package.domain = org.barinventory" >> buildozer.spec
          echo "source.dir = ." >> buildozer.spec
          echo "source.include_exts = py,db" >> buildozer.spec
          echo "version = 1.0" >> buildozer.spec
          echo "requirements = python3,kivy,sqlite3" >> buildozer.spec
          echo "android.api = 31" >> buildozer.spec
          echo "android.minapi = 21" >> buildozer.spec
          echo "android.ndk = 25b" >> buildozer.spec
          echo "android.arch = arm64-v8a" >> buildozer.spec
          echo "orientation = portrait" >> buildozer.spec
          echo "android.permissions = INTERNET, WRITE_EXTERNAL_STORAGE, READ_EXTERNAL_STORAGE" >> buildozer.spec
          echo "android.accept_sdk_license = True" >> buildozer.spec
          echo "" >> buildozer.spec
          echo "[buildozer]" >> buildozer.spec
          echo "log_level = info" >> buildozer.spec

      - name: Сборка APK
        run: |
          buildozer -v android debug

      - name: Загрузка APK
        uses: actions/upload-artifact@v4
        with:
          name: bar-inventory-apk
          path: bin/*.apk