name: Сборка APK

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Buildozer
        run: |
          pip install buildozer

      - name: Create buildozer.spec
        run: |
          cat > buildozer.spec << 'EOF'
          [app]
          title = Bar Inventory
          package.name = barinventory
          package.domain = org.barinventory
          source.dir = .
          source.include_exts = py,db
          version = 1.0
          requirements = python3,kivy,sqlite3,openpyxl
          p4a.hook = hooks/hook-sqlite3.py
          android.api = 31
          android.minapi = 21
          android.ndk = 25b
          android.arch = arm64-v8a
          orientation = portrait
          android.permissions = INTERNET, WRITE_EXTERNAL_STORAGE, READ_EXTERNAL_STORAGE
          android.accept_sdk_license = True

          [buildozer]
          log_level = info
          EOF

      - name: Accept Android SDK licenses manually
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          yes | sdkmanager --licenses
          yes | sdkmanager "platform-tools" "build-tools;31.0.0" "platforms;android-31"

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: bar-inventory-apk
          path: bin/*.apk