name: Сборка APK

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Buildozer and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk
          pip install --upgrade pip
          pip install Cython==0.29.36 buildozer

      - name: Create buildozer.spec
        run: |
          echo "[app]
          title = Bar Inventory
          package.name = barinventory
          package.domain = org.barinventory
          source.dir = .
          source.include_exts = py,db
          version = 1.0
          requirements = python3,kivy,sqlite3
          p4a.hook = hooks/hook-sqlite3.py
          android.api = 31
          android.minapi = 21
          android.ndk = 25b
          android.archs = arm64-v8a
          orientation = portrait
          android.permissions = INTERNET, WRITE_EXTERNAL_STORAGE, READ_EXTERNAL_STORAGE
          android.accept_sdk_license = True

          [buildozer]
          log_level = info" > buildozer.spec

      - name: Build APK
        run: buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: bar-inventory-apk
          path: bin/*.apk