name: Сборка APK

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            build-essential \
            libffi-dev \
            libssl-dev \
            libxml2-dev \
            libxslt1-dev \
            libjpeg-dev \
            zlib1g-dev \
            python3-pip \
            autoconf \
            automake \
            libtool \
            pkg-config \
            libltdl-dev

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install Cython==0.29.36
          pip install buildozer

      - name: Create buildozer.spec
        run: |
          echo "[app]
          title = Bar Inventory
          package.name = barinventory
          package.domain = org.barinventory
          source.dir = .
          source.include_exts = py,db,png,jpg,kv,atlas
          source.include_patterns = assets/*,res/*,libs/*
          version = 1.0
          requirements = python3,kivy==2.2.1,openssl,sqlite3
          android.api = 33
          android.minapi = 21
          android.ndk = 23c
          android.ndk_path = /home/runner/android-ndk-r23c
          android.sdk_path = /home/runner/android-sdk
          android.arch = arm64-v8a
          android.p4a_dir = /home/runner/.local/bin/p4a
          orientation = portrait
          fullscreen = 0
          android.permissions = INTERNET,WRITE_EXTERNAL_STORAGE,READ_EXTERNAL_STORAGE
          android.wakelock = False
          android.meta_data = 
          android.activity_attributes = 
          android.allow_backup = True
          android.filename = BarInventory-1.0-arm64-v8a-debug.apk
          android.accept_sdk_license = True
          android.adaptive_icon = 0
          
          [buildozer]
          log_level = 2" > buildozer.spec

      - name: Download Android SDK and NDK
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
          mkdir -p android-sdk/cmdline-tools
          unzip cmdline-tools.zip -d android-sdk/cmdline-tools
          mv android-sdk/cmdline-tools/cmdline-tools android-sdk/cmdline-tools/latest
          
          wget https://dl.google.com/android/repository/android-ndk-r23c-linux.zip -O android-ndk.zip
          unzip android-ndk.zip
          mv android-ndk-r23c android-ndk

      - name: Set up environment variables
        run: |
          echo "ANDROID_SDK_HOME=$PWD/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=$PWD/android-ndk" >> $GITHUB_ENV
          echo "PATH=$PWD/android-sdk/cmdline-tools/latest/bin:$PWD/android-ndk:$PATH" >> $GITHUB_ENV

      - name: Accept Android licenses
        run: |
          yes | $PWD/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Build APK with Buildozer
        run: |
          buildozer android clean
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: bar-inventory-apk
          path: bin/*.apk