name: Сборка APK

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Buildozer and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk build-essential libffi-dev libssl-dev libxml2-dev libxslt1-dev libjpeg8-dev zlib1g-dev
          pip install --upgrade pip setuptools wheel
          pip install Cython==0.29.36 buildozer

      - name: Create buildozer.spec
        run: |
          echo "[app]
          title = Bar Inventory
          package.name = barinventory
          package.domain = org.barinventory
          source.dir = .
          source.include_exts = py,db
          version = 1.0
          requirements = python3,kivy,sqlite3
          android.api = 34
          android.minapi = 21
          android.ndk = 25b
          android.archs = arm64-v8a
          orientation = portrait
          android.permissions = INTERNET, WRITE_EXTERNAL_STORAGE, READ_EXTERNAL_STORAGE
          android.accept_sdk_license = True
          
          [buildozer]
          log_level = 2" > buildozer.spec

      - name: Build APK
        run: |
          # Создадим минимальный main.py, если его нет
          if [ ! -f "main.py" ]; then
            echo 'print("Hello from APK")' > main.py
          fi
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: bar-inventory-apk
          path: bin/*.apk