name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout код
        uses: actions/checkout@v4
        
      - name: Установка зависимостей
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential python3-dev libffi-dev libssl-dev libmpg123-0 libsqlite3-dev libbz2-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good
          pip install --upgrade pip
          pip install buildozer Cython==0.29.33

      - name: Создание buildozer.spec
        run: |
         echo "[app]
          title = Bar Inventory
          package.name = barinventory
          package.domain = org.barinventory
          source.dir = .
          source.include_exts = py,png,jpg,kv,atlas,db
          version = 1.0
          requirements = python3,kivy,sqlite3,openpyxl
          orientation = portrait
          android.permissions = INTERNET,WRITE_EXTERNAL_STORAGE,READ_EXTERNAL_STORAGE

          [buildozer]
          log_level = info
          warn_on_root = 1

          [android]
          android.api = 31
          android.minapi = 21
          android.ndk = 25b
          android.arch = arm64-v8a" > buildozer.spec

      - name: Автоматически принять лицензии Android SDK
        run: |
          yes | sdkmanager --licenses
          yes | sdkmanager "platform-tools" "build-tools;31.0.0" "platforms;android-31"

      - name: Сборка APK
        run: |
          buildozer -v android debug

      - name: Загрузка APK
        uses: actions/upload-artifact@v4
        with:
          name: bar-inventory-apk
          path: bin/*.apk